-- name: \\#FAFF20\\Only Up 64
-- description: \\#FAFF20\\Only Up 64\\#FFF\\ v1.6.0\nBy \\#65834B\\Kaze\\#FFF\\ and \\#0868EC\\thelegendofzenia\\#FFF\\\n\nThis whole mod is one big, tall level that takes around 25 minutes to complete - if you don't fall. Climb the biggest level ever made! (as of today)\n\nPorted to sm64coopdx by \\#E01F2D\\DizzyThermal\\#FFF\\ and \\#0868EC\\Cooliokid956\\#FFF\\
-- incompatible: romhack
